### PR TITLE
Resolve #116 WP REST API support

### LINKED ISSUE #116: Add WP REST API support
Is there any roadmap to add WP REST API support for this plugin?

### PR DESCRIPTION
**Pull request by johnwatkins0**
Resolves #116

This change adds a REST API endpoint at `[site-url]/wp-json/wp/v2/popular-posts/`. The endpoint accepts most of the same args as the widget. The arguments can be viewed (where the plugin is activated) at `[site-url]/wp-json/wp/v2/`.

### CODE REVIEW

**Comment by johnwatkins0** [comment]
Thanks, @cabrerahector! Sorry about the space-to-tab autoformat faux pas. The two commits I sent just sent up (1) restore the original formatting of the modified files, and (2) do an extra check of the WPP_Query posts before running that for loop. 

Happy to revisit if you see anything else. Awesome plugin, by the way.

**Comment by cabrerahector** [comment]
Better late than never: thank you! (for your kinds comments and for contributing) :)

I've reviewed the changes and everything seems in order. I've merged your PR and will add a couple of changes to the controller.

Again, thanks!

**Comment by apparition47** [comment]
Was having trouble locating the endpoint. Found the REST url here: `https://<SITE-URL>/wp-json/wordpress-popular-posts/v1`

**Comment by cabrerahector** [comment]
Alright guys, here it is: [REST API Endpoints](https://github.com/cabrerahector/wordpress-popular-posts/wiki/8.-REST-API-Endpoints).

Suggestions are welcome.

**Pull request merged**
