### PR TITLE
add __() around $content for qTranslate-x

### PR DESCRIPTION
**Pull request by dingerkingh**
I added __() around $content so it would be compatible with qTranslate-x. Not sure if this is a change you would want to make to your code or not.

### CODE REVIEW

**Comment by cabrerahector** [comment]
Hi there!

Thanks for contributing! I'm a bit busy at the moment, so it'll be awhile before I get the chance to review the proposed changes.

From a quick look at the code though, it seems you're translating the entire HTML list instead of translating only the title, excerpt, etc. as WPP currently does with qTranslate?

**Comment by dingerkingh** [comment]
Yes - I believe that is what the __() is doing. However, when I added __() around just the title, excerpt, etc - it never actually translated the text. I was only able to get it to translate when adding it around the entire html. 

I could be way off the mark and maybe this breaks functionality of other features. In my instance - it worked so I thought I would run it by you. Thanks again for the plugin!

**Comment by cabrerahector** [comment]
Alright. I'll check qTranslate-x's docs and see if there's a better way to integrate it with WPP without breaking anything (including legacy qTranslate support) :)

**Comment by dingerkingh** [comment]
I would delete the pull request. This breaks functionality. Sorry to waste your time...

**Comment by cabrerahector** [comment]
Hi @dingerkingh, I haven't had the chance to check this yet. What does it break?

**Comment by dingerkingh** [comment]
Well - it appears that when in use the only thing it will display is the date. I use the widget to show the title and number of hits - but after changing that it would only display a date next to the title. An interesting side note thought is that I completely reinstalled the plugin and it did the same thing. No hit counter - just the date. I have cleared the caches and what not but didn't seem to fix it either. I am still not convinced it isn't the cache still showing the old data though...

**Comment by cabrerahector** [comment]
If you reverted the modification and the HTML output was still broken, then it must be something else. Are you using a caching plugin? If so, clear its cache as well and check again.

**Pull request closed without merging**
