### PR TITLE
Add: exclude traffic with cookies

### PR DESCRIPTION
**Pull request by sekedus**
## What?

Exclude all internal traffic (log views) with cookies.

## Why?

Every visit made an employee can skews log views data, and becomes an even larger problem when working with larger business.

## How?

Store cookies name to `wpp-json`, check if cookies exists, `do_request = false;`

Fix this issue: [Exclude internal traffic with cookie](https://wordpress.org/support/topic/exclude-internal-traffic-with-cookie/)

## Testing Instructions
1. Open [this site (WP Test by TasteWP)](https://symptomaticbone.s4-tastewp.com/wp-admin/) and login (**automatically deleted after 48 hours**)
  - Username: admin 
  - Password: MesT-4qTcF8
2. Go to **Settings** > **WordPress Popular Posts** > **Tools**
3. Scroll to **Data** > **Exclude log views with cookies** > **Yes**
4. **Cookies field name** > type `internal_user`
5. Open [site post](https://symptomaticbone.s4-tastewp.com/2020/08/05/hello-world/)
6. Open DevTools > Console,
7. Add cookies `internal_user` with this script
```` javascript
function setCookie(cname, cvalue, exdays, cdomain) {
  var d = new Date();
  d.setTime(d.getTime() + (exdays*24*60*60*1000));
  var expires = "expires="+ d.toUTCString();
  document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/ ; domain=" + cdomain;
}
setCookie("internal_user", "internal", 365, location.hostname.replace(/^www\./i, "")); //One year
````
8. Reload the page.
9. Check [wpp stats](https://symptomaticbone.s4-tastewp.com/wp-admin/options-general.php?page=wordpress-popular-posts&tab=stats)
ㅤ

### CODE REVIEW

**Comment by cabrerahector** [comment]
Hey @sekedus,

Thanks for your contribution, however [as I said on the forum](https://wordpress.org/support/topic/exclude-internal-traffic-with-cookie/#post-17242446) (and as stated on this [FAQ](https://github.com/cabrerahector/wordpress-popular-posts/wiki/5.-FAQ#i-want-your-plugin-to-have-x-or-y-functionality-can-it-be-done)) I'm not interested in adding features that only a handful of people (if any) will use.

**Comment by sekedus** [comment]
> I'm not interested in adding features that only a handful of people (if any) will use.

Hasn't excluding internal traffic using cookies been used by many people for a long time?

Analytics: [exclude internal traffic cookies](https://www.google.com/search?q=exclude%20internal%20traffic%20cookies)
Blogspot: [blogspot "Don't track my views for this blog"](https://www.google.com/search?q=blogspot%20%22Don%27t%20track%20my%20views%20for%20this%20blog%22)

**Comment by cabrerahector** [comment]
WordPress Popular Posts has been since 2008 and in all these years there's been only __one__ person who has ever shown interest in such a feature, and that person is you :P

So yeah, I honestly don't believe that this is something other people would be interested in.

**Comment by sekedus** [comment]
Ok, as expected `2008`.

**Pull request closed without merging**
